services:
  - type: web
    name: salto-quantico-backend
    runtime: python
    rootDir: backend
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
